service: meu-primeiro-app-serverless

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true
          integration: lambda
          # requestTemplates:
            # application/json: '{"statusCode": 200}'
