apiVersion: v1
kind: Service

metadata:
  name: meu-app-service

spec:
  type: ClusterIP
  selector:
    app: meu-app
  ports: 
    - port: 80 # Porta que receberá a requisição
      targetPort: 80 # Porta para redirecionar para o pod da label app: meu-app